# This file was *autogenerated* from the file signature.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_128 = Integer(128); _sage_const_51 = Integer(51); _sage_const_36 = Integer(36); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_0b10010010100010101010101001 = Integer(0b10010010100010101010101001)
from hash16 import hash

p = _sage_const_2 **_sage_const_128  + _sage_const_51 
K = GF(p)

a = _sage_const_2
b = _sage_const_36

E = EllipticCurve(K, [a, b])

G = E.gens()[_sage_const_0 ]
q = G.order()

print(f"Generator of the curve : {G} of order {q}")

def secrandom(length) :
    return ZZ.random_element(_sage_const_1 , p)

def signature_keygen():
    secret_key = secrandom(q)
    public_key = secret_key * G
    return secret_key, public_key

def sign(secret_key, m) :
    e = hash(m) % q
    k = secrandom(q)
    r = ZZ((k * G)[_sage_const_1 ]) % q
    s = ZZ(e * secret_key * r) * inverse_mod(k, q) % q
    sigma = (r, s)
    return sigma

def verify(public_key, signature, m) :
    r, s = signature
    t = inverse_mod(s, q) % q
    e = hash(m)
    u = r * e * t % q
    r_prime = u * public_key
    success = r == r_prime[_sage_const_1 ]
    return success


m = _sage_const_0b10010010100010101010101001 

priv, pub = signature_keygen()

signature = sign(priv, m)
ver = verify(pub, signature, m)
print(ver)

