

# This file was *autogenerated* from the file signature.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_128 = Integer(128); _sage_const_51 = Integer(51); _sage_const_36 = Integer(36); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_0b1001001010 = Integer(0b1001001010)
import random as rd
from hash16 import hash

p = _sage_const_2 **_sage_const_128  + _sage_const_51 
K = GF(p)

a = _sage_const_2 
b = _sage_const_36 

E = EllipticCurve(K, [a, b])

print(E.order() - _sage_const_2 **_sage_const_128 )

G = E.gens()[_sage_const_0 ]
q = G.order()

print(G)

def secrandom(length) :
    return rd.randint(_sage_const_1 , _sage_const_2 **length - _sage_const_1 )

def signature_keygen():
    secret_key = secrandom(q)
    public_key = secret_key * G
    return secret_key, public_key

def sign(secret_key, m) :
    e = hash(m)
    k = secrandom(q)
    r = (k * G)[_sage_const_1 ]
    s = (e * r * secret_key) * k.inverse() 
    sigma = (r, s)

def verify(public_key, signature, m) :
    r, s = signature
    t = inverse_mod(s, q)
    e = hash(m)
    r_prime = (e * r * t * public_key)[_sage_const_1 ]
    success = r == r_prime
    return success


m = _sage_const_0b1001001010 

priv, pub = signature_keygen()

signature = sign(priv, m)
ver = verify(pub, m, signature)
print(ver)

